# Form implementation generated from reading ui file 'MonitoringUi.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Monitoring(object):
    def setupUi(self, Monitoring):
        Monitoring.setObjectName("Monitoring")
        Monitoring.setEnabled(False)
        Monitoring.resize(400, 300)
        font = QtGui.QFont()
        font.setFamily("B Koodak")
        font.setBold(True)
        font.setWeight(75)
        Monitoring.setFont(font)
        Monitoring.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        Monitoring.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)

        self.retranslateUi(Monitoring)
        QtCore.QMetaObject.connectSlotsByName(Monitoring)

    def retranslateUi(self, Monitoring):
        _translate = QtCore.QCoreApplication.translate
        Monitoring.setWindowTitle(_translate("Monitoring", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Monitoring = QtWidgets.QWidget()
    ui = Ui_Monitoring()
    ui.setupUi(Monitoring)
    Monitoring.show()
    sys.exit(app.exec())
